CREATE TABLE `register` (
`name` varchar(20) NOT NULL,
`email` varchar(30) NOT NULL,
`username` varchar(20) NOT NULL,
`password` varchar(50) NOT NULL,
`state` varchar(15) NOT NULL,
`image` varchar(100) NOT NULL,
`id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;